# important features for the pictures
dataset: cub
attributes: cub
attributes_pth: data/cub/cub_attributes.txt
cluster_feature_method: linear # [kmeans, random, linear, similarity]
# model_type: open_clip
model_type: clip
# model_size: hf-hub:laion/CLIP-ViT-L-14-laion2B-s32B-b82K
# model_size: ViT-L/14@336px
# model_size: ViT-L/14
model_size: ViT-L/14
mahalanobis: true
division_power: 3
linear_epochs: 5000
reinit: false # True/False
num_attributes: full # [16, 32, 64, 128, 256, 512]
seed: 0

# optimization parameters
lr: 0.0001
batch_size: 32
epochs: -2000

# model structure
linear_model: [linear, linear] 
score_model: [linear] 