# important features for the pictures
dataset: food
attributes: food
cluster_feature_method: linear # [kmeans, random, linear]
# model_type: clip
# model_size: ViT-B/32
# model_type: open_clip
model_type: clip
# model_size: hf-hub:laion/CLIP-ViT-L-14-laion2B-s32B-b82K
model_size: ViT-L/14
mahalanobis: false
division_power: 2
linear_epochs: 200
reinit: true # True/False
num_attributes: full # [16, 32, 64, 128, 256, 512]
seed: 0

# optimization parameters
lr: 0.0001
batch_size: 4096
epochs: -2000

# model structure
linear_model: [linear, bn, linear] 
score_model: [bn, linear]